### ISSUE TITLE
eMap画出来的图变量少了一个

### ISSUE THREAD

**Issue by cityvigil** [taiyun/recharts#16]
load(url('http://yzhou.org/recharts/ChinaGDP.RData'))
plot(eMap(ChinaGDP, opt=list(title=list(text='2008~2010年大陆各省GDP占全国百分数'))))

在R3.1.0环境下，运行
ChinaGDP 数据集有三个变量，只画出来两个，第一个变量丢失。
另外在鼠标移动过去的时候 ，里面的有一个变量的值没有显示 ：）

**Comment by Cherry1218** [comment]
请问您在R中安装好了？

**Comment by cityvigil** [comment]
我好久没有用了。以前是装好过

**Comment by Cherry1218** [comment]
我后来安装好了，但是用的是
install.packages(
  'recharts',
  repos = c('http://yihui.name/xran', 'http://cran.rstudio.com')
)
我才发现这个和我安装的recharts的功能不同
