### ISSUE TITLE
ERROR: unable to collate and parse R files for package ‘recharts’

### ISSUE THREAD

**Issue by BobbyXu2014** [taiyun/recharts#23]
install_github(‘taiyun/recharts’)
Downloading github repo taiyun/recharts@master
 Installing recharts
“C:/PROGRA~1/R/R-31~1.2/bin/i386/R” –vanilla CMD \
 INSTALL \
“C:\Users\AppData\Local\Temp\RtmpYPKjOV\devtools1cc8a6d5719\taiyun-recharts-8e4da23″ \
–library=”C:/Program Files/R/R-3.1.2/library” \
–install-tests 

* installing *source* package ‘recharts’ …
** R
 Error in parse(outFile) : 句法分析器31行里不能有多字节字符
ERROR: unable to collate and parse R files for package ‘recharts’
* removing ‘C:/Program Files/R/R-3.1.2/library/recharts’
Error: Command failed (1)

**Comment by BobbyXu2014** [comment]
Linux上可以按照成功，但windows下就是安装不成功！！

**Comment by Fluxionist** [comment]
Same problem on R3.2 Windows 8.1 x64.

**Comment by wangyanglffw** [comment]
R3.0.2老版本也安装不成功

**Comment by taiyun** [comment]
Please try:

```
install_github('ramnathv/htmlwidgets')
install_github('rstudio/htmltools')
install_github('taiyun/recharts@htmlwidgets')
```

**Comment by wangyanglffw** [comment]
谢谢，已经解决！

**Comment by Fluxionist** [comment]
works like a charm. Thanks!

**Comment by austinmike** [comment]
多谢，终于解决了！

**Comment by moranren** [comment]
>devtools::install_github('taiyun/recharts')
错误: Failed to install 'unknown package' from GitHub:
   An unknown option was passed in to libcurl
这是什么错误，该如何解决？

**Comment by moranren** [comment]
devtools::install_local("/usr/local/software/recharts-master.zip")

Error in parse(outFile) : 句法分析器28行里不能有多字节字符
ERROR: unable to collate and parse R files for package ‘recharts’
* removing ‘/usr/lib64/R/library/recharts’
