### ISSUE TITLE
Refactor this package based on CRAN htmlwidgets

### ISSUE THREAD

**Issue by wush978** [taiyun/recharts#25]
Dear Maintainers,

I notice that some active R package developers publish this package for integrating html/js library with R.

Currently, rechrats does not work on shiny application, so maybe it is a time to refactor this package based on [this framework](http://cran.r-project.org/web/packages/htmlwidgets/index.html).

How do you think?

**Comment by yihui** [comment]
I spent a few days working on that last year and got a simple prototype working, but I'm quite busy recently so I cannot spend much time there. I hope someone can pick up the work.

**Comment by yihui** [comment]
I just pushed my prototype to Github: https://github.com/yihui/recharts Please let me know if you have any comments.

**Comment by wush978** [comment]
Dear @yihui ,

I have read your vignette. It is a great start! Will you or one of existed maintainer of recharts manage the refactor/develop the recharts based on htmlwidget? Personally I want to know where should I discuss the technical details and give the PR for https://github.com/yihui/recharts.

**Comment by yihui** [comment]
I believe rewrite is easier than factoring out the old code. You are welcome to discuss ideas and send PRs to https://github.com/yihui/recharts but as I said, I do not have much time recently, so please try to start with smaller ideas and PRs, otherwise it is unlikely that I will be able to review a PR of 500 lines of code :)

**Comment by KuiMing** [comment]
Hello Yihui,

I noticed that it seems easier to build recharts on this framework. I begin to figure out how to do this, but I need some time. Anyway, I really want to give effort to build recharts because Echart is really amazing!

**Comment by yihui** [comment]
@KuiMing It definitely is :)
