### ISSUE TITLE
could not find function "mergeList"

### ISSUE THREAD

**Issue by lichangzai** [taiyun/recharts#31]
> source("~/echartR.R")
> library(recharts)
> names(iris) = gsub("\\.", "", names(iris))
> echartR(data=iris,x=~SepalLength,y=~PetalWidth,series = ~Species,
+         type = 'scatter')
Error in echartR(data = iris, x = ~SepalLength, y = ~PetalWidth, series = ~Species,  : 
  could not find function "mergeList"

**Comment by yummyZhou** [comment]
Please provide me the exact plotting code,

At present, you need to clarify the chart type in your plot code as the following examples:
eBar for bar chart; 
ePoints for scatter chart;
eMap for map;
eLine for line chart;
eRadar for radar chart;
ePie for pie chart;
eArea for erea chart;

and some other chart type will be added in later

**Comment by yihui** [comment]
将来可以统一用略紧凑的语法 `devtools::install_github('taiyun/recharts')`
