### ISSUE TITLE
双Y轴

### ISSUE THREAD

**Issue by c101088** [taiyun/recharts#38]
在下查看R中帮助文档好久，似乎没有发现如何绘制双Y轴的图形。如果可以，作者可否给一示例？谢啦~~~

**Comment by Lchiffon** [comment]
请看这里
http://taiyun.github.io/recharts/interface.html#section-3.2.2

安装请使用:

```r
devtools::install_github("taiyun/recharts@dev")
```

**Comment by c101088** [comment]
真真是非常感谢！之前只是把您在上个版本的recharts包中的echart.js源码以及部分关联名称改掉，在本地自己适配一个基于echart3.0的R包，用起来虽然会报错，但是能出图。打算暑假仔细研究一下，哈哈哈，阁下真是迅速。再次感谢！




在2017年07月4日 16:55，Dawei Lang<notifications@github.com> 写道：

请看这里
http://taiyun.github.io/recharts/interface.html#section-3.2.2

安装请使用:

devtools::install_github("taiyun/recharts@dev")

**Comment by GofunTR** [comment]
@c101088  十分感谢！
